version: 2.1

jobs:
  release_android:
    docker:
      - image: cimg/base:2023.09
        auth:
          username: bookbubcloner
          password: $DOCKER_HUB_PASSWORD
    resource_class: small
    working_directory: ~/branch-testing
    environment:
      BBWORKSPACE: "/home/circleci"
    steps:
      - run: echo "I am building a release"

workflows:
  release:
    jobs:
      - release_android
